apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-student-insert
spec:
  replicas: 1 # Runs on both of your t3.medium nodes
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
spec:
  backoffLimit: 4
  template:
    spec:  
      containers:
      - name: app-container
        image: ${FULL_IMAGE_NAME}
      restartPolicy: Never
        #ports:
        #- containerPort: 8080 # Change this to the port your Python app uses
---
apiVersion: v1
kind: Service
metadata:
  name: my-python-service
spec:
  type: ClusterIP # This creates a real AWS Load Balancer for you
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
